In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:\\HoonsCode\\Beginning\\crawling\\table_goobne.csv")

In [3]:
df.head()

   Unnamed: 0      name                         address
0           0     흥덕지구점  경기도 용인시 기흥구  흥덕1로 79번길 9, 105호
1           1      휘닉스점     강원도 평창군 봉평면 무이리 694-14번지 1층
2           2       후곡점           경기도 고양시 일산서구  일산로 576
3           3  효자중화산1호점            전라북도 전주시완산구  안행로 154
4           4       회덕점               경기도 광주시  이배재로 108

In [4]:
df

      Unnamed: 0      name                                  address
0              0     흥덕지구점           경기도 용인시 기흥구  흥덕1로 79번길 9, 105호
1              1      휘닉스점              강원도 평창군 봉평면 무이리 694-14번지 1층
2              2       후곡점                    경기도 고양시 일산서구  일산로 576
3              3  효자중화산1호점                     전라북도 전주시완산구  안행로 154
4              4       회덕점                        경기도 광주시  이배재로 108
5              5     황상인의점                         경상북도 구미시  여현로 80
6              6       화천점                     강원도 화천군 화천읍 중앙로 37번지
7              7       화양점                서울특별시 광진구   능동로19길 53, 1층
8              8     화성반월점              경기도 화성시  효행로1265번길 17, 101호
9              9     화성마도점                   경기도 화성시 마도면 두곡서길 35 1층
10            10     화성남양점    경기도 화성시 남양동 남양도시개발구역 2-1블럭 화성남양상가 103
11            11     화서1동점             경기도 수원시 팔달구 화서동 219-1번지 101호
12            12     화북삼양점                        제주도 제주시  진동로1길 13
13            13     화곡본동점                      서울특별시 강서구 화곡동 29-27
14            14     화곡4동점                   서울특별시 강서구 화곡4동 827-8번지
15            15       홍천점                  강원도 홍천군 홍천읍 연봉리 502-5번지
16            16     홍제2호점            서울특별시 서대문구  문화촌길 34, 아동 지층 1호
17            17     홍제1호점                   서울특별시 서대문구 홍제동 155-6번지
18            18     홍은2동점                   서울특별시 서대문구  백련사길 6, 1층
19            19      홍성읍점                 충청남도 홍성군 홍성읍 문화로 33번길 10
20            20      홍농읍점                전라남도 영광군 홍농읍 상하길 33, 102호
21            21       호평점                       경기도 남양주시 호평동 615-6
22            22     호원1호점  경기도 의정부시 호원동 419 상가동 1층 104,105호(현대아파트)
23            23      호수동점             경기도 안산시 단원구  광덕2로 194-8,108호
24            24      호매실점       경기도 수원시 권선구  서수원로523번길 30-35, 101호
25            25       현풍점                대구광역시 달성군 현풍면 현풍중앙로14길 85
26            26     향남지구점                  경기도 화성시 향납읍 행정서로3길 4-16
27            27    향남2지구점     경기도 화성시 향남읍 상신하길로298번길 7-27(1층 111호)
28            28     행신2호점               경기도 고양시 덕양구  중앙로 478, 109호
29            29       행당점                        서울특별시 성동구  행당로 79
...          ...       ...                                      ...
995          995     거여2동점                    서울특별시 송파구 거여동 35번지 1층
996          996       거모점                     경기도 시흥시 도일로 143(거모동)
997          997     개포4동점                서울특별시 강남구  개포로 20길 32, 1층
998          998     개포2동점             서울특별시 강남구   선릉로12길 5, 102-나호
999          999     개봉1동점                   서울특별시 구로구  고척로21길 17-1
1000        1000   개금1,2동점                     부산광역시 부산진구  엄광로 52-1
1001        1001       강화점                   인천광역시 강화군 강화읍 강화대로 199
1002        1002     강저지구점                        충청북도 제천시 영천동 2209
1003        1003     강원횡성점                    강원도 횡성군 횡성읍 북천리115-52
1004        1004     강원장평점                  강원도 평창군 용평면 금송1길 49, 1층
1005        1005   강릉홍제내곡점                   강원도 강릉시  남산초교길 12번길 16
1006        1006     강릉포남점                   강원도 강릉시  강릉대로 457번길 25
1007        1007     강릉택지점                강원도 강릉시   원대로 128번길, 107호
1008        1008     강릉유천점             강원도 강릉시  선수촌로79-1, 101호(홍제동)
1009        1009     강릉성덕점                       강원도 강릉시 입암동 498-12
1010        1010     강남세곡점      서울특별시 강남구  밤고개로 227, 지상1층 105호,106호
1011        1011       감정점                   경기도 김포시  북변1로 36, 106호
1012        1012     갈현2동점                  서울특별시 은평구 갈현2동 506-33번지
1013        1013       갈매점      경기도 구리시 갈매순환로204 8-52, 101호 전면 왼쪽상가
1014        1014       갈말점               강원도 철원군 갈말읍 명성로139번길 13-22
1015        1015       간성점                       강원도 고성군 간성읍 간성로 67
1016        1016       간석점                     인천광역시  남동구   예술로 278
1017        1017       가평점                  경기도 가평군 가평읍 오리나무길 41-15
1018        1018     가좌1호점                         인천광역시 서구 가좌동 7번지
1019        1019       가정점          인천광역시 서구  염곡로498번안길 11-1, 1층 일부
1020        1020       가양점           서울특별시 강서구 가양동 1479-3번지 1층 104호
1021        1021       가산점                     서울특별시 금천구 가산동 151-25
1022        1022     가락본동점                 서울특별시 송파구  송파대로30길 41-34
1023        1023     가곡수동점                     경기도 남양주시 수동면 비룡로 716
1024        1024  [폐]경북성주점

[1025 rows x 3 columns]